apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-adopt-config
  namespace: pet-adopt-dev
spec:
  data:
    POTGRES_USER: "postgres"
    POSTGRES_DB: "petdb"
    GRAFANA_USER: "petgf"
    DB_PORT: "5433"
    BACKEND_PORT: "5555"
    FRONTEND_PORT: "3000"
    PROMETHEUS_PORT: "9090"
    GRAFANA_PORT: "3001"
    VITE_API_URL: "http://localhost:5555/api"